name: portfolio-dashboard

services:
  portfolio-db:
    image: ${USE_LOCAL_IMAGES:+localhost/library/}postgres:16-alpine
    container_name: portfolio-db
    ports:
      - '${DB_PORT:-5434}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_DB: ${POSTGRES_DB:-portfolio}
    volumes:
      - ${DB_VOLUME_PATH:-portfolio_db_data}:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s
    networks:
      - portfolio_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '${DB_CPU_LIMIT:-1}'
          memory: ${DB_MEMORY_LIMIT:-512M}

volumes:
  portfolio_db_data:
    driver: local

networks:
  portfolio_network:
    driver: bridge
