import { PrismaClient } from '../client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  const hashedPassword = await bcrypt.hash('demo', 10);

  const user = await prisma.user.upsert({
    where: { username: 'demo' },
    update: {},
    create: {
      username: 'demo',
      password: hashedPassword,
      email: 'demo@portfolio.com',
    },
  });

  console.log('Created demo user:', user.username);

  const stocks = [
    {
      symbol: 'HDFCBANK.NS',
      name: 'HDFC Bank',
      sector: 'Financial Sector',
      purchasePrice: 1490,
      quantity: 50,
      investment: 74500,
      portfolioPercent: 5,
      exchange: 'NSE',
      peRatioTTM: 18.5,
      marketCap: '12,00,000 Cr',
      latestEarnings: 69181,
      revenueTTM: 321990,
      ebitdaTTM: 106757,
      ebitdaPercent: 33,
      pat: 69181,
      patPercent: 21,
      cfoMarch24: -3983,
      cfo5Years: 85155,
      debtToEquity: 7,
      bookValue: 693,
      revenueGrowth3Y: 30.19,
      ebitdaGrowth3Y: 50.23,
      profitGrowth3Y: 26.25,
      marketCapGrowth3Y: 10,
      cfoToEbitda: -2680,
      cfoToPat: -1737,
      stage2: 'Yes',
    },
    {
      symbol: 'BAJFINANCE.NS',
      name: 'Bajaj Finance',
      sector: 'Financial Sector',
      purchasePrice: 6466,
      quantity: 15,
      investment: 96990,
      portfolioPercent: 6,
      exchange: 'NSE',
      peRatioTTM: 32.1,
      marketCap: '4,00,000 Cr',
      latestEarnings: 15375,
      revenueTTM: 62279,
      ebitdaTTM: 43336,
      ebitdaPercent: 70,
      pat: 15375,
      patPercent: 25,
      cfoMarch24: 82415,
      cfo5Years: 201273,
      debtToEquity: 4,
      bookValue: 1253,
      revenueGrowth3Y: 27.26,
      ebitdaGrowth3Y: 68.23,
      profitGrowth3Y: 48.42,
      marketCapGrowth3Y: 13,
      cfoToEbitda: 53,
      cfoToPat: 19,
      stage2: 'No',
    },
    {
      symbol: 'ICICIBANK.NS',
      name: 'ICICI Bank',
      sector: 'Financial Sector',
      purchasePrice: 1143,
      quantity: 70,
      investment: 80010,
      portfolioPercent: 5,
      exchange: 'NSE',
      peRatioTTM: 15.2,
      revenueTTM: 174379,
      ebitdaTTM: 57238,
      ebitdaPercent: 33,
      pat: 47368,
      patPercent: 27,
      cfoMarch24: 13765,
      cfo5Years: 4332,
      debtToEquity: 6,
      bookValue: 366,
      revenueGrowth3Y: 21.4,
      ebitdaGrowth3Y: 28.66,
      profitGrowth3Y: 34.02,
      marketCapGrowth3Y: 24,
      cfoToEbitda: 416,
      cfoToPat: 344,
      stage2: 'Yes',
    },
    {
      symbol: 'INFY.NS',
      name: 'Infosys',
      sector: 'Tech Sector',
      purchasePrice: 1450,
      quantity: 100,
      investment: 145000,
      portfolioPercent: 9,
      exchange: 'NSE',
      peRatioTTM: 24.5,
      revenueTTM: 2067,
      ebitdaTTM: 412,
      ebitdaPercent: 20,
      pat: 343,
      patPercent: 17,
      cfoMarch24: 262,
      cfo5Years: 902,
      freeCashFlow5Years: -281,
      debtToEquity: 0,
      bookValue: 183,
      revenueGrowth3Y: 52.78,
      ebitdaGrowth3Y: 19.75,
      profitGrowth3Y: 30.16,
      marketCapGrowth3Y: 2,
      cfoToEbitda: 157,
      cfoToPat: 131,
      stage2: 'Yes',
    },
    {
      symbol: 'TCS.NS',
      name: 'TCS',
      sector: 'Tech Sector',
      purchasePrice: 3500,
      quantity: 30,
      investment: 105000,
      portfolioPercent: 7,
      exchange: 'NSE',
      peRatioTTM: 28.3,
      revenueTTM: 36485,
      ebitdaTTM: 6426,
      ebitdaPercent: 18,
      pat: 4654,
      patPercent: 13,
      cfoMarch24: 5670,
      cfo5Years: 16058,
      freeCashFlow5Years: 11468,
      debtToEquity: 0,
      bookValue: 676,
      revenueGrowth3Y: 42.13,
      ebitdaGrowth3Y: 18.72,
      profitGrowth3Y: 33.26,
      marketCapGrowth3Y: 27,
      cfoToEbitda: 113,
      cfoToPat: 82,
      stage2: 'No',
    },
    {
      symbol: 'DMART.NS',
      name: 'DMart',
      sector: 'Consumer Sector',
      purchasePrice: 3800,
      quantity: 25,
      investment: 95000,
      portfolioPercent: 6,
      exchange: 'NSE',
      peRatioTTM: 65.2,
      revenueTTM: 54813,
      ebitdaTTM: 4379,
      ebitdaPercent: 8,
      pat: 2687,
      patPercent: 5,
      cfoMarch24: 2746,
      cfo5Years: 9404,
      freeCashFlow5Years: -169,
      debtToEquity: 0,
      bookValue: 288,
      revenueGrowth3Y: 28.13,
      ebitdaGrowth3Y: 8.22,
      profitGrowth3Y: 32.13,
      marketCapGrowth3Y: 17,
      cfoToEbitda: 159,
      cfoToPat: 98,
      stage2: 'No',
    },
    {
      symbol: 'TATAPOWER.NS',
      name: 'Tata Power',
      sector: 'Power Sector',
      purchasePrice: 245,
      quantity: 200,
      investment: 49000,
      portfolioPercent: 3,
      exchange: 'NSE',
      peRatioTTM: 22.1,
      revenueTTM: 63489,
      ebitdaTTM: 11057,
      ebitdaPercent: 17,
      pat: 3746,
      patPercent: 6,
      cfoMarch24: 12596,
      cfo5Years: 42175,
      freeCashFlow5Years: 10285,
      debtToEquity: 2,
      bookValue: 101,
      revenueGrowth3Y: 23.4,
      ebitdaGrowth3Y: 16.0,
      profitGrowth3Y: 48.56,
      marketCapGrowth3Y: 56,
      cfoToEbitda: 88,
      cfoToPat: 30,
      stage2: 'No',
    },
    {
      symbol: 'POLYCAB.NS',
      name: 'Polycab',
      sector: 'Pipe Sector',
      purchasePrice: 5200,
      quantity: 20,
      investment: 104000,
      portfolioPercent: 7,
      exchange: 'NSE',
      peRatioTTM: 28.9,
      revenueTTM: 20129,
      ebitdaTTM: 2546,
      ebitdaPercent: 13,
      pat: 1795,
      patPercent: 9,
      cfoMarch24: 1296,
      cfo5Years: 4732,
      freeCashFlow5Years: 3285,
      debtToEquity: 0,
      bookValue: 546,
      revenueGrowth3Y: 27.07,
      ebitdaGrowth3Y: 12.62,
      profitGrowth3Y: 26.46,
      marketCapGrowth3Y: 55,
      cfoToEbitda: 196,
      cfoToPat: 139,
      stage2: 'Yes',
    },
  ];

  for (const stockData of stocks) {
    await prisma.stock.upsert({
      where: {
        userId_symbol: {
          userId: user.id,
          symbol: stockData.symbol,
        },
      },
      update: stockData,
      create: {
        userId: user.id,
        ...stockData,
      },
    });
  }

  console.log('Created', stocks.length, 'stocks with full fundamentals');
  console.log('Seeding complete!');
}

main()
  .catch(e => {
    console.error('Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
